# Generated by Django 5.2.10 on 2026-01-18 02:53

import dashboard.apps.fintech.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=dashboard.apps.fintech.models.generate_account_number, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(help_text='Número do cartão (fictício, 16 dígitos)', max_length=16, unique=True, verbose_name='Número do Cartão')),
                ('pin', models.CharField(max_length=4, verbose_name='PIN')),
                ('expiration_date', models.DateField(verbose_name='Validade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='fintech.account', verbose_name='Conta Associada')),
            ],
            options={
                'verbose_name': 'Cartão Fictício',
                'verbose_name_plural': 'Cartões Fictícios',
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Dispositivo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Dispositivo')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('owner_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_devices', to='fintech.account', verbose_name='Conta do Proprietário')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transferência'), ('DEPOSIT', 'Depósito'), ('WITHDRAW', 'Saque'), ('PAYMENT', 'Pagamento'), ('PIX_SENT', 'Pix Enviado'), ('PIX_RECEIVED', 'Pix Recebido'), ('PURCHASE', 'Compra Marketplace')], default='TRANSFER', max_length=20, verbose_name='Tipo')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('transaction_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Hash SHA256')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='fintech.account', verbose_name='Destinatário')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='fintech.account', verbose_name='Remetente')),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to='fintech.iotdevice', verbose_name='Device Origem')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PixKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=10, verbose_name='Tipo de Chave')),
                ('key_value', models.CharField(max_length=255, unique=True, verbose_name='Valor da Chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_keys', to='fintech.account', verbose_name='Conta Associada')),
            ],
            options={
                'verbose_name': 'Chave Pix',
                'verbose_name_plural': 'Chaves Pix',
                'unique_together': {('key_type', 'key_value')},
            },
        ),
    ]
