# Generated by Django 5.2.10 on 2026-01-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Limite de Crédito'),
        ),
        migrations.AddField(
            model_name='account',
            name='invested_collateral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Garantia Travada'),
        ),
    ]
